# Generated by Django 5.2.1 on 2025-09-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='voter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_image',
            field=models.ImageField(blank=True, null=True, upload_to='voter_images/'),
        ),
    ]
