# Generated by Django 5.2.1 on 2025-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0002_remove_voter_voter_id_voter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='last_name',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
