# Generated by Django 5.2.1 on 2025-09-16 03:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0003_rename_first_name_voter_name_remove_voter_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.AutoField(primary_key=True, serialize=False)),
                ('election_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('closed', 'Closed')], default='upcoming', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elections',
            },
        ),
        migrations.AlterField(
            model_name='voter',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.CASCADE, to='voting_site.election')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('party', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, to='voting_site.position')),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='ElectionVoter',
            fields=[
                ('election_voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_voted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('election', models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.CASCADE, to='voting_site.election')),
                ('voter', models.ForeignKey(db_column='voter_id', on_delete=django.db.models.deletion.CASCADE, to='voting_site.voter')),
            ],
            options={
                'db_table': 'election_voters',
                'unique_together': {('voter', 'election')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, to='voting_site.candidate')),
                ('position', models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, to='voting_site.position')),
                ('voter', models.ForeignKey(db_column='voter_id', on_delete=django.db.models.deletion.CASCADE, to='voting_site.voter')),
            ],
            options={
                'db_table': 'votes',
                'unique_together': {('voter', 'position')},
            },
        ),
    ]
