# Generated by Django 5.2.1 on 2025-09-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0004_election_alter_voter_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_image',
            field=models.ImageField(blank=True, null=True, upload_to='voter_images/'),
        ),
    ]
