# Generated by Django 5.2.1 on 2025-09-18 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0005_alter_voter_voter_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['candidate_name']},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting_site.position'),
        ),
        migrations.AlterField(
            model_name='electionvoter',
            name='election',
            field=models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voting_site.election'),
        ),
        migrations.AlterField(
            model_name='electionvoter',
            name='voter',
            field=models.ForeignKey(db_column='voter_id', on_delete=django.db.models.deletion.CASCADE, related_name='election_participations', to='voting_site.voter'),
        ),
        migrations.AlterField(
            model_name='position',
            name='election',
            field=models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='voting_site.election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_site.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='position',
            field=models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_site.position'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(db_column='voter_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_site.voter'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('election', 'position_name')},
        ),
    ]
