# Generated by Django 5.2.1 on 2025-09-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0006_alter_candidate_options_alter_election_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
