# Generated by Django 5.2.1 on 2025-09-21 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0007_candidate_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='candidate_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
