# Generated by Django 5.2.1 on 2025-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0008_election_candidate_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='previous_vote_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
