# Generated by Django 5.2.1 on 2025-09-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_site', '0009_vote_previous_vote_hash_vote_vote_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('closed', 'Closed')], default='upcoming', max_length=10),
        ),
    ]
